(define (calculator)
  (display "Simple Calculator\n")
  (display "Operations: + - * /\n")
  (display "Enter 'q' to quit\n\n")
  
  (let loop ()
    (display "Enter first number: ")
    (let ((num1 (read)))
      (when (not (eq? num1 'q))
        (display "Enter operator (+, -, *, /): ")
        (let ((op (read)))
          (display "Enter second number: ")
          (let ((num2 (read)))
            (case op
              ((+) (display (format "Result: ~a\n" (+ num1 num2))))
              ((-) (display (format "Result: ~a\n" (- num1 num2))))
              ((*) (display (format "Result: ~a\n" (* num1 num2))))
              ((/) (if (= num2 0)
                       (display "Error: Division by zero\n")
                       (display (format "Result: ~a\n" (/ num1 num2)))))
              (else (display "Error: Invalid operator\n")))
            (loop)))))))

(calculator)